// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYjVrbkTuExWC9dy5s-sxjaSaRiR-Ax4',
    appId: '1:359871865531:web:48c4b4cb8d24b98faf3f9e',
    messagingSenderId: '359871865531',
    projectId: 'chat-app-50a9f',
    authDomain: 'chat-app-50a9f.firebaseapp.com',
    storageBucket: 'chat-app-50a9f.appspot.com',
    measurementId: 'G-FWC754B4N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm_ieEFoKA4wNCipREl4Ayn7uXpmaC0zc',
    appId: '1:359871865531:android:de84695c06c30905af3f9e',
    messagingSenderId: '359871865531',
    projectId: 'chat-app-50a9f',
    storageBucket: 'chat-app-50a9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYY7bJS8DhDRiWsyCoNQxshJvsf5whdDM',
    appId: '1:359871865531:ios:92964d6e4da373d3af3f9e',
    messagingSenderId: '359871865531',
    projectId: 'chat-app-50a9f',
    storageBucket: 'chat-app-50a9f.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYY7bJS8DhDRiWsyCoNQxshJvsf5whdDM',
    appId: '1:359871865531:ios:92964d6e4da373d3af3f9e',
    messagingSenderId: '359871865531',
    projectId: 'chat-app-50a9f',
    storageBucket: 'chat-app-50a9f.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXYjVrbkTuExWC9dy5s-sxjaSaRiR-Ax4',
    appId: '1:359871865531:web:5637ca39a4ed2953af3f9e',
    messagingSenderId: '359871865531',
    projectId: 'chat-app-50a9f',
    authDomain: 'chat-app-50a9f.firebaseapp.com',
    storageBucket: 'chat-app-50a9f.appspot.com',
    measurementId: 'G-JCVM12J5ZN',
  );
}
